//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
namespace Ghostwriter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public author()
        {
            this.titleauthors = new HashSet<titleauthor>();
        }

        [DisplayName("Author ID")]
        public string au_id { get; set; }
        [DisplayName("Last Name")]
        public string au_lname { get; set; }
        [DisplayName("First Name")]
        public string au_fname { get; set; }
        [DisplayName("Phonenumber")]
        public string phone { get; set; }
        [DisplayName("Address")]
        public string address { get; set; }
        [DisplayName("City")]
        public string city { get; set; }
        [DisplayName("State")]
        public string state { get; set; }
        [DisplayName("Zip Code")]
        public string zip { get; set; }
        [DisplayName("Contract")]
        public bool contract { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Titles")]
        public virtual ICollection<titleauthor> titleauthors { get; set; }
    }
}
