//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
namespace Ghostwriter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        [DisplayName("Discount Type")]
        public string discounttype { get; set; }
        [DisplayName("Store ID")]
        public string stor_id { get; set; }
        [DisplayName("Low Quantity")]
        public Nullable<short> lowqty { get; set; }
        [DisplayName("High Quantity")]
        public Nullable<short> highqty { get; set; }
        [DisplayName("Discount")]
        public decimal discount1 { get; set; }
        [DisplayName("Store")]
        public virtual store store { get; set; }
    }
}
