//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Ghostwriter.Models
{
    using System;
    using System.Collections.Generic;

    public partial class employee
    {
        [DisplayName("Employee ID")]
        public string emp_id { get; set; }
        [DisplayName("First Name")]
        public string fname { get; set; }
        [DisplayName("Minit")]
        public string minit { get; set; }
        [DisplayName("Last Name")]
        public string lname { get; set; }
        [DisplayName("Job ID")]
        public short job_id { get; set; }
        [DisplayName("Job Level")]
        public Nullable<byte> job_lvl { get; set; }
        [DisplayName("Publisher ID")]
        public string pub_id { get; set; }
        [DisplayName("Hired")]
        public System.DateTime hire_date { get; set; }
        [DisplayName("Job")]
        public virtual job job { get; set; }
        [DisplayName("Publisher")]
        public virtual publisher publisher { get; set; }
    }
}
