//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Ghostwriter.Models
{
    using System;
    using System.Collections.Generic;

    public partial class pub_info
    {
        [DisplayName("Publisher ID")]
        public string pub_id { get; set; }
        [DisplayName("Logo")]
        public byte[] logo { get; set; }
        [DisplayName("Information")]
        public string pr_info { get; set; }

        [DisplayName("Publisher")]
        public virtual publisher publisher { get; set; }
    }
}
