//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Ghostwriter.Models
{
    using System;
    using System.Collections.Generic;

    public partial class roysched
    {
        [DisplayName("Title ID")]
        public string title_id { get; set; }
        [DisplayName("Lo Range")]
        public Nullable<int> lorange { get; set; }
        [DisplayName("Hi Range")]
        public Nullable<int> hirange { get; set; }
        [DisplayName("Royalty")]
        public Nullable<int> royalty { get; set; }

        [DisplayName("Title")]
        public virtual title title { get; set; }
    }
}
