//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Ghostwriter.Models
{
    using System;
    using System.Collections.Generic;

    public partial class sale
    {
        [DisplayName("Store ID")]
        public string stor_id { get; set; }
        [DisplayName("Order")]
        public string ord_num { get; set; }
        [DisplayName("Date")]
        public System.DateTime ord_date { get; set; }
        [DisplayName("Quantity")]
        public short qty { get; set; }
        [DisplayName("Payment")]
        public string payterms { get; set; }
        [DisplayName("Title ID")]
        public string title_id { get; set; }
        [DisplayName("Store")]
        public virtual store store { get; set; }
        [DisplayName("Title")]
        public virtual title title { get; set; }
    }
}
