//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Ghostwriter.Models
{
    using System;
    using System.Collections.Generic;

    public partial class sysdiagram
    {
        [DisplayName("Name")]
        public string name { get; set; }
        [DisplayName("Principal ID")]
        public int principal_id { get; set; }
        [DisplayName("Diagram ID")]
        public int diagram_id { get; set; }
        [DisplayName("Version")]
        public Nullable<int> version { get; set; }
        [DisplayName("Definition")]
        public byte[] definition { get; set; }
    }
}
