//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Ghostwriter.Models
{
    using System;
    using System.Collections.Generic;

    public partial class title
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public title()
        {
            this.sales = new HashSet<sale>();
            this.titleauthors = new HashSet<titleauthor>();
        }
        [DisplayName("Title ID")]
        public string title_id { get; set; }
        [DisplayName("Title")]
        public string title1 { get; set; }
        [DisplayName("Type")]
        public string type { get; set; }
        [DisplayName("Publisher ID")]
        public string pub_id { get; set; }
        [DisplayName("Price")]
        public Nullable<decimal> price { get; set; }
        [DisplayName("Advance")]
        public Nullable<decimal> advance { get; set; }
        [DisplayName("Royalty")]
        public Nullable<int> royalty { get; set; }
        [DisplayName("YTD Sales")]
        public Nullable<int> ytd_sales { get; set; }
        [DisplayName("Notes")]
        public string notes { get; set; }
        [DisplayName("Published")]
        public System.DateTime pubdate { get; set; }
        [DisplayName("Publisher")]
        public virtual publisher publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Sales")]
        public virtual ICollection<sale> sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Author(s)")]
        public virtual ICollection<titleauthor> titleauthors { get; set; }
        public virtual roysched roysched { get; set; }
    }
}